services:
    ladoo_general_ledge.repository.invoice:
        class: Ladoo\GeneralLedgeBundle\Repository\InvoiceRepository
        factory: [ "@doctrine.orm.default_entity_manager", "getRepository" ]
        arguments:
            - LadooGeneralLedgeBundle:Invoice

    ladoo_general_ledge.controller.invoice_rest:
        class: Ladoo\GeneralLedgeBundle\Controller\InvoiceRestController
        arguments:
            - "@ladoo_general_ledge.repository.invoice"
            - "@doctrine.orm.default_entity_manager"
            - "@jms_serializer.serializer"
            - "@validator"
        calls:
            - { method: setViewHandler, arguments: [ "@fos_rest.view_handler" ] }

    ladoo_general_ledge.repository.transaction:
            class: Ladoo\GeneralLedgeBundle\Repository\TransactionRepository
            factory: [ "@doctrine.orm.default_entity_manager", "getRepository" ]
            arguments:
                - LadooGeneralLedgeBundle:Transaction

        ladoo_general_ledge.controller.invoice_rest:
            class: Ladoo\GeneralLedgeBundle\Controller\TransactionRestController
            arguments:
                - "@ladoo_general_ledge.repository.transaction"
            calls:
                - { method: setViewHandler, arguments: [ "@fos_rest.view_handler" ] }