security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory: ~

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            stateless: true
            pattern: ^/api/
            http_basic:
                provider: in_memory

        main:
            anonymous: ~
