<?php

namespace Ladoo\GeneralLedgeBundle\Repository;

/**
 * InvoiceLineItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceLineItemRepository extends \Doctrine\ORM\EntityRepository
{
}
